version: '3'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: city
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

  web:
    image: web
    build:
      context: .
    command: >
        bash -c 'python app.py'
    volumes:
      - ./backend:/home/backend/
    ports:
      - '5000:5000'
    depends_on:
      - db
